name: Test Tagging

# on: pull_request
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
          
      - run: |
          CHANGES="$(GITHUB_TOKEN=${{ secrets.GH_TOKEN }} ./changelog.sh)"
          echo working 
          echo "$CHANGES"
          git fetch --unshallow --tags
          MOST_RECENT_TAG="$(git describe --tags $(git rev-list --tags --max-count=1))"
          echo "$MOST_RECENT_TAG"
          FEATURE="$(echo "${CHANGES}" | grep -ic 'feature' || true)"
          echo "$FEATURE"
          git config --global user.email "adampurcell7t@gmail.com"
          git config --global user.name "Adam Purcell"
          if [ "$FEATURE" -gt 0 ]; then
              NEW_TAG="$(echo "$MOST_RECENT_TAG" | awk -F. '{OFS="."; $(NF-1)+=1; $NF=0; print $0}')"
              git tag -a "$NEW_TAG" -m "$CHANGES"
          else
              NEW_TAG="$(echo "$MOST_RECENT_TAG" | awk -F. '{OFS="."; $NF+=1; print $0}')" 
              git tag -a "$NEW_TAG" -m "$CHANGES"
          fi
          git push --tags